"""inicio pagina de campeonatos

Revision ID: 0c2e42d76d07
Revises: b15bff6b12da
Create Date: 2026-09-09 07:45:53.600760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2e42d76d07'
down_revision: Union[str, Sequence[str], None] = 'b15bff6b12da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
